#!/usr/bin/env ruby
# File: script/console
irb = RUBY_PLATFORM =~ /(:?mswin|mingw)/ ? 'irb.bat' : 'irb'

libs =  " -r irb/completion"
libs << " -r #{File.join(File.expand_path(File.dirname(__FILE__)), "..", "lib", "rdf_context.rb")}"
puts "Loading rdf_context gem"
exec "#{irb} #{libs} --simple-prompt"
